# Type code for classes here

class ItemToPurchase:
    def __init__(self, item_name = "none", item_price = 0.0, item_quantity = 0):
        self.item_name = item_name
        self.item_price = item_price
        self.item_quantity = item_quantity

    def print_item_cost(self):
        total_cost = item_price * item_quantity
        print(f"{item_name} {item_quantity} @ ${item_price} = ${total_cost}")

if __name__ == "__main__":
    # Type main section of code here
    item1 = ItemToPurchase()
    print("Enter the item name:")
    item1.item_name = input()
    print("Enter the item price:")
    item1.item_price = input()
    print("Enter the item item quantity:")
    item1.item_quantity = input()

    item2 = ItemToPurchase()
    print("Enter the item name:")
    item2.item_name = input()
    print("Enter the item price:")
    item2.item_price = input()
    print("Enter the item item quantity:")
    item2.item_quantity = input()

    print("TOTAL COST")
    item1.print_item_cost()
    item2.print_item_cost
    total_cost = (item1.item_price * item1.item_quantity) + (item2.item_price * item2.item_quantity)

    print(f"Total: ${total_cost}")
